# ruff.toml
line-length = 88
target-version = "py310"

exclude = [
    ".venv",
    ".cache",
    "node_modules"
]

[lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = [
    "E501", # line too long
    "B008", # noop on function defaults
]

[lint.isort]
combine-as-imports = true
force-wrap-aliases = true
split-on-trailing-comma = true

[format]
quote-style = "double"
indent-style = "space"
